[package]
name = "eekwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0.216", features = ["derive"] }
serde_json = "1.0.133"
sysinfo = "0.33.0"
regex = "^1.11.0"
lettre = "0.11.11"
chrono = "0.4.39"
