name: Rust

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: Linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
          - name: Linux-aarch64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross
          - name: Windows-x86_64
            runner: windows-latest
            target: x86_64-pc-windows-gnu
            command: cross
          - name: FreeBSD-x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-freebsd
            command: cross
          # cargo
          - name: MacOs-aarch64
            runner: macOS-latest
            target: aarch64-apple-darwin
            command: cargo
          - name: MacOS-x86_64
            runner: macOS-latest
            target: x86_64-apple-darwin
            command: cargo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      # Only install cross if we need it
      # Install via cargo-binstall which I found faster
      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross

      - name: Build Binary
        run: ${{ matrix.command }} build --verbose --locked --release --target ${{ matrix.target }}


      